using System;
using System.Windows.Forms;

namespace Game
{
    internal static class Program
    {
        [STAThread]
        private static void Main()
        {
            string MapPacman = @"
WWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WFFFPFFFFFFFFWWWFFFFFFKFFFFFW
WFWWWWFWWWWWFWWWFWWWWWFWWWWFW
WEWWWWFWWWWWFWWWFWWWWWFWWWWEW
WFWWWWFWWWWWFWWWFWWWWWFWWWWFW
WFFFFFFFFFFFFFFFFFFFFFFFFFFFW
WFWWWWFWWFWWWWWWWWWFWWFWWWWFW
WFFFFFFWWFFFFWWWFFFFWWFFFFFFW
WWWWWWFWWWWW WWW WWWWWFWWWWWW
     WFWWWWW WWW WWWWWFW     
     WFWWW      B  WWWFW     
     WFWWW WWWDWWW WWWFW     
WWWWWWFWWW WW I WW WWWFWWWWWW
      FF   WWWWWWW   FF      
WWWWWWFWW           WWFWWWWWW
     WFWW WWWWWWWWW WWFW     
     WFWW WWWWWWWWW WWFW     
WWWWWWFWW WWWWWWWWW WWFWWWWWW
WFFFFFFFFFFFFWWWFFFFFFFFFFFFW
WFWWWWFWWWWWFWWWFWWWWWFWWWWFW
WFWWWWFWWWWWFWWWFWWWWWFWWWWFW
WEFFWWFFFFFFFFFFFFFFFFFWWFFEW
WWWFWWFWWFWWWWWWWWWFWWFWWFWWW
WWWFWWFWWFWWWWWWWWWFWWFWWFWWW
WFFFFFFWWFFFFWWWFFFFWWFFFFFFW
WFWWWWWWWWWWFWWWFWWWWWWWWWWFW
WFWWWWWWWWWWFWWWFWWWWWWWWWWFW
W             S             W
WWWWWWWWWWWWWWWWWWWWWWWWWWWWW
";
        Game.CreateMap(MapPacman);
            Application.Run(new PacManWindow());
        }
    }
}